stages:
  - check
  - build
  - test

flake8:
  image: rustdocker/rust:stable
  stage: check
  allow_failure: true
  script:
    - apt-get update
    - apt-get install -y flake8
    - flake8 .

cargo:build:
  image: rustdocker/rust:stable
  stage: build
  script:
    - apt-get update
    - apt-get install -y capnproto libsqlite3-dev
    - cargo install capnpc
    - cargo build --all-features --verbose
  artifacts:
    paths:
      - target
    expire_in: 6h
  only:
    - master

doc:build:
  image: ubuntu:latest
  stage: build
  script:
    - cd docs
    - apt-get update && apt-get install -y python3-dev python3-pip
    - pip3 install --upgrade pip
    - pip3 install sphinx sphinx_rtd_theme sphinxcontrib-napoleon sphinxcontrib-fulltoc pycapnp cloudpickle
    - make html

pytest:
  image: rustdocker/rust:stable
  stage: test
  script:
    - apt-get update
    - apt-get install -y capnproto python3-dev python3-pip libsqlite3-dev
    - pip3 install --upgrade pip
    - pip3 install pycapnp cloudpickle pytest pytest-timeout cbor
    - RAIN_TEST_BIN=${PWD}/target/release/rain pytest -x -v --timeout=20
  artifacts:
    when: on_failure
    paths:
      - tests/pytests/work
    expire_in: 1d
  only:
    - master

cargo:test:
  image: rustdocker/rust:stable
  stage: test
  script:
    - apt-get update
    - apt-get install -y capnproto libsqlite3-dev
    - cargo install capnpc
    - cargo test --all-features
  only:
    - master
